// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgaclcviakwzbdzlvxwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnYWNsY3ZpYWt3emJkemx2eHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODg1NTAsImV4cCI6MjA3MTg2NDU1MH0.3SzXUFYUotgZCyY6HuvfTVEgxWqq7PvtGr2mrfc672Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});